repos:
  - repo: https://github.com/python/black.git
    rev: 22.6.0
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: ['--max-line-length=88', '--ignore=E203,W503', 'exclude=*__init__*']